package com.kanha.controller;

import java.util.Map;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.kanha.model.Student;

@Controller
public class StudentOperationsController {

	/*
	 	NOTE: 	TWO WAY DATA BINDING
	 	
	 	 1. FORM DATA BINDING : Using @ModelAttribute(-) annotation
	 	 	
	 	 	- Passing Form data to controller class handler method as Model class object using @ModelAttribute(-) annotation.
	 	 	- It binds all request parameter value generated by form page to a Model class/ Java Bean class object.
	 	 	
	 	 2. PARAMETER DATA BINDING : Using @RequestParam annotation
	 	 
	 	 	- It binds each request parameter value to each parameter of handler method.
	 	 	
	 	 	
	 	NOTE: 
	 		- For Data Rendering, to place model attributes in Shared memory like Map<String, Object>
	 		- For Data Binding, to place form data into Model Class Object, @ModelAttributes("stud") ClassName object
	 	
	 */
	
	
	
	@GetMapping("/")
	public String showHomePage() {
		System.out.println("StudentOperationsController.showHomePage()");
		// return LVN
		return "welcome";
	}

	@GetMapping("/register") // for launching the form page
	public String showStudentRegistrationPage(@ModelAttribute("stud") Student st) {
		System.out.println("StudentOperationsController.showStudentRegistrationPage()");
		// return LVN
		return "student_register_form";
	}

	@PostMapping("/register") // for submitting the form page
	public String processStudentRegistration(@ModelAttribute("stud") Student st, Map<String, Object> map) {
		
		System.out.println("StudentOperationsController.processStudentRegistration()::" + st);

		// write b.logic
		String result = null;
		if (st.getAvg() >= 75)
			result = "First Class with Dist";
		else if (st.getAvg() >= 60)
			result = "First Class ";
		else if (st.getAvg() >= 50)
			result = "Second class";
		else if (st.getAvg() >= 35)
			result = "Third class";
		else
			result = "fail";
		// keep the result in model attribute
		map.put("resultMsg", result);
		// return LVN
		return "display";
	}

}
